name: Scheduled Worker Run

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:
    inputs:
      max_items:
        description: "Max items per source"
        required: false
        default: "50"
      limit_sources:
        description: "Limit to first N sources"
        required: false
        default: ""

jobs:
  run-worker-once:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libdrm2 \
              libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 \
              libasound2 libatspi2.0-0 libxshmfence1 libx11-xcb1

      - name: Install Python dependencies
        working-directory: apps/worker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Write Savee cookies to file
        run: |
          mkdir -p apps/worker
          if [ -n "${{ secrets.COOKIES_URL }}" ]; then
            echo "Downloading cookies from COOKIES_URL";
            curl -fsSL "${{ secrets.COOKIES_URL }}" -o apps/worker/savee_cookies.json;
          elif [ -n "${{ secrets.COOKIES_JSON_MINIFIED }}" ]; then
            echo "Writing cookies from COOKIES_JSON_MINIFIED";
            printf '%s' "${{ secrets.COOKIES_JSON_MINIFIED }}" > apps/worker/savee_cookies.json;
          else
            echo "No cookies provided. Set COOKIES_URL or COOKIES_JSON_MINIFIED secrets.";
            exit 1;
          fi
          echo "Validating cookies JSON";
          jq empty apps/worker/savee_cookies.json

      - name: Run one scrape cycle
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          AMQP_URL: ${{ secrets.AMQP_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          COOKIES_PATH: apps/worker/savee_cookies.json
        working-directory: apps/worker
        run: |
          MAX_ITEMS="${{ github.event.inputs.max_items }}"; [ -z "$MAX_ITEMS" ] && MAX_ITEMS="50";
          if [ -n "${{ github.event.inputs.limit_sources }}" ]; then
            python -m app.cli --max-items "$MAX_ITEMS" --limit-sources "${{ github.event.inputs.limit_sources }}";
          else
            python -m app.cli --max-items "$MAX_ITEMS";
          fi
